repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
        args: [--max-line-length=80, --extend-ignore=E203]
        exclude: 'examples/'
-   repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
    -   id: isort
        args: [--check-only, --diff]
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black
        args: [--check, --line-length=80]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        args: [--install-types, --non-interactive, --ignore-missing-imports]